catalogue/urls.py
from django.urls import path
from . import views  # on importe les vues de l'app catalogue

app_name = 'catalogue'

urlpatterns = [
    # Liste des artistes
    path('artist/', views.index, name='artist-index'),


    # Fiche d'un artiste (détail)
    path('artist/<int:artist_id>/', views.show, name='artist-show'),

    # Formulaire de modification
    path('artist/edit/<int:artist_id>/', views.edit, name='artist-edit'),

    # Formulaire de création
    path('artist/create/', views.create, name='artist-create'),

    # Suppression
    path('artist/delete/<int:artist_id>/', views.delete, name='artist-delete'),
]

reservations/urls.py
#from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import include, path
from catalogue.views import home



urlpatterns = [
    #path('', RedirectView.as_view(url='/artist/', permanent=False)),
    path('catalogue/', include('catalogue.urls')),
    path('admin/', admin.site.urls),
    path('', home, name='home'), 
]

catalogue/models/artist.py
from django.db import models

#create your modele here

class Artist(models.Model):
    firstname = models.CharField(max_length = 60)
    lastname = models.CharField(max_length=60)
    
    def __str__(self):
        return self.firstname +" "+self.lastname
    
    class Meta:
        db_table = "artists"

catalogue/forms/ArtistForm.py
from django import forms
from catalogue.models import Artist

class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = [
                'firstname',
                'lastname'
        ]

catalogue/views/artist.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404

from catalogue.models import Artist
from catalogue.forms.ArtistForm import ArtistForm




# Create your views here.
def index(request):
	artists = Artist.objects.all()
	
	return render(request, 'artist/index.html', {
		'artists':artists,
	})

def show(request, artist_id):
	try:
		artist = Artist.objects.get(id=artist_id)
	except Artist.DoesNotExist:
		raise Http404('Artist inexistant');
		
	return render(request, 'artist/show.html', {
		'artist':artist,
	})


def edit(request, artist_id):
    # fetch the object related to passed id
    artist = Artist.objects.get(id=artist_id)

    # pass the object as instance in form
    form = ArtistForm(request.POST or None, instance=artist)

    if request.method == 'POST':
        method = request.POST.get('_method', '').upper()

        if method == 'PUT':
            # save the data from the form and
            # redirect to detail_view
            if form.is_valid():
                form.save()

                return render(request, "artist/show.html", {
                    'artist': artist,
                })

    return render(request, 'artist/edit.html', {
        'form': form,
        'artist': artist,
    })


def create(request):
    # On crée un formulaire vide ou pré-rempli avec les données POST
    form = ArtistForm(request.POST or None)

    if request.method == 'POST':
        # Si on a soumis le formulaire
        if form.is_valid():
            form.save()  # Enregistre un nouvel artiste dans la DB
            return redirect('catalogue:artist-index')  # Retour à la liste

    # Si on arrive en GET ou que le formulaire n'est pas valide
    return render(request, 'artist/create.html', {
        'form': form,
    })


def delete(request, artist_id):
    artist = get_object_or_404(Artist, id =artist_id)
    if request.method =="POST":
        method = request.POST.get('_method', '').upper()
        if method =='DELETE':
            artist.delete()

            return redirect('catalogue:artist-index')
    return render(request, 'artist/show.html', {'artist': artist,})

catalogue/views/home.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

catalogue/templates/artist/create.html
{%extends 'layouts/base.html'%}

{%block title %} Modifier un artist {% endblock %}

{% block content %}
    <H2>Ajouter un artiste</H2>
    <form action="{%url 'catalogue:artist-create' %}" method="post">
        {% csrf_token %}

        {{ form }}
        <button> Ajouter</button>
        <a href="{%url 'catalogue:artist-index' %}"> Annuler</a>

    </form>
    <nav><a href="{%url 'catalogue:artist-index' %}"> Retour à la l'index</a></nav>
{% endblock %}

catalogue/templates/artist/edit.html
{%extends 'layouts/base.html'%}

{%block title %} Modifier un artist {% endblock %}

{% block content %}
    <H2>Modifier un artiste</H2>
    <form action="{%url 'catalogue:artist-edit' artist.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name ="_method" value="PUT">
        {{ form }}
        <button> Modifier</button>
        <a href="{%url 'catalogue:artist-show' artist.id %}"> Annuler</a>

    </form>
    <nav><a href="{%url 'catalogue:artist-index' %}"> Retour à la l'index</a></nav>
{% endblock %}

catalogue/templates/artist/index.html
{% extends 'layouts/base.html' %}

{% block title %}Liste des artistes{% endblock %}

{% block content %}
    <h2>{{ title }}</h2>
    <ul>
        <li><a href="{% url 'catalogue:artist-create' %}">Ajouter</a></li>
    </ul>

    <table>
        <thead>
            <tr>
                <th>Firstname</th>
                <th>Lastname</th>
            </tr>
        </thead>
        <tbody>
        {% for artist in artists %}
            <tr>
                <td>{{ artist.firstname }}</td>
                <td>
		<a href="{% url 'catalogue:artist-show' artist.id %}">{{ artist.lastname }}</a>
                </td>
            </tr>
        {% empty %}
	    <tr>
	         <td colspan="2">Sorry, no artist in the database.</td>
	    </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

catalogue/templates/artist/show.html
{% extends 'layouts/base.html' %}

{% block title %}Fiche d’un artiste{% endblock %}

{% block content %}
    <h2>{{ artist.firstname }} {{ artist.lastname }}</h2>
    <div><a href="{% url 'catalogue:artist-edit' artist.id %}">Modifier</a></div>
    <form method="post" action="{% url 'catalogue:artist-delete' artist.id %}"
        onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ?')">
        {% csrf_token %}

        <input type="hidden" name="_method" value="DELETE">

        <button>Supprimer</button>
    </form>

    <nav><a href="{% url 'catalogue:artist-index' %}">Retour à l'index</a></nav>
{% endblock %}

catalogue/templates/home.html
{% extends "layouts/base.html" %}

{% block title %}Accueil{% endblock %}

{% block content %}
<h1>Bienvenue sur l’application</h1>

<p>Page d’accueil du projet.</p>

<a href="{% url 'catalogue:artist-index' %}">
    Voir les artistes
</a>
{% endblock %}

catalogue/templates/layouts/base.html
<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<title>Projet réservations - {% block title %}Bienvenue{% endblock %}</title>
</head>
<body>
<div class="container">
        {% block content %}{% endblock %}
</div>
</body>
</html>